// Build script: collects Markdown content, bundles the React app with esbuild,
// and writes one self-contained HTML page to dist/index.html.
// React and ReactDOM load from cdnjs as UMD globals.
import { build } from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';

const root = path.dirname(new URL(import.meta.url).pathname);
const contentDir = path.join(root, 'content');
const genDir = path.join(root, 'src', 'generated');
fs.mkdirSync(genDir, { recursive: true });

// 1. Collect chapters (content/chapters/*.md, sorted by filename)
const chDir = path.join(contentDir, 'chapters');
const chapterFiles = fs.readdirSync(chDir).filter(f => f.endsWith('.md')).sort();
const chapters = chapterFiles.map(f => fs.readFileSync(path.join(chDir, f), 'utf8'));

// 2. Collect reference files (content/*.md)
const refs = {};
for (const f of fs.readdirSync(contentDir)) {
  if (f.endsWith('.md')) refs[f.replace(/\.md$/, '')] = fs.readFileSync(path.join(contentDir, f), 'utf8');
}

fs.writeFileSync(
  path.join(genDir, 'content.ts'),
  '// AUTO-GENERATED by build.mjs. Edit files in /content instead.\n' +
  `export const chapterSources: string[] = ${JSON.stringify(chapters)};\n` +
  `export const refSources: Record<string, string> = ${JSON.stringify(refs)};\n`
);

// 3. Bundle
const globalsPlugin = {
  name: 'globals',
  setup(b) {
    b.onResolve({ filter: /^react(-dom)?(\/client)?$/ }, a => ({ path: a.path, namespace: 'g' }));
    b.onLoad({ filter: /.*/, namespace: 'g' }, a => ({
      contents: a.path.startsWith('react-dom') ? 'module.exports = window.ReactDOM' : 'module.exports = window.React',
      loader: 'js',
    }));
  },
};

const result = await build({
  entryPoints: [path.join(root, 'src', 'main.tsx')],
  bundle: true,
  minify: process.argv.includes('--dev') ? false : true,
  write: false,
  format: 'iife',
  target: 'es2019',
  jsx: 'transform',
  jsxFactory: 'React.createElement',
  jsxFragment: 'React.Fragment',
  plugins: [globalsPlugin],
  logLevel: 'warning',
});

const js = result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
const css = fs.readFileSync(path.join(root, 'src', 'styles.css'), 'utf8');

const html = `<title>Git for Developers</title>
<meta name="description" content="An interactive book that teaches Git from your first commit to professional workflows.">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,400;12..96,500;12..96,600;12..96,700&family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600;1,8..60,400&family=JetBrains+Mono:wght@400;500;600&display=swap">
<style>
${css}
</style>
<div id="root"><div class="boot">Loading the book…</div></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/18.3.1/umd/react.production.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.3.1/umd/react-dom.production.min.js"></script>
<script>
${js}
</script>
`;

fs.mkdirSync(path.join(root, 'dist'), { recursive: true });
fs.writeFileSync(path.join(root, 'dist', 'index.html'), html);
const kb = (Buffer.byteLength(html) / 1024).toFixed(0);
const words = [...chapters, ...Object.values(refs)].join(' ').split(/\s+/).length;
console.log(`dist/index.html  ${kb} KB  | ${chapters.length} chapters | ~${words.toLocaleString()} words of content`);
